# HTTP & System Configuration
quarkus.http.port=8080

# Virtual Threading
quarkus.virtual-threads.enabled=true

# Datasource Configuration
quarkus.datasource.devservices.enabled=false
quarkus.datasource.jdbc.max-size=16

## H2
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1

## Postgres
#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=postgres
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/batchdb

# Hibernate ORM Configuration
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.jdbc.statement-batch-size=4000
quarkus.hibernate-orm.order_inserts=true
quarkus.hibernate-orm.order_updates=true

# Logging & Banner Configuration
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c] (%t) %s%e%n
quarkus.log.console.level=INFO
quarkus.banner.path=banner.txt
quarkus.log.startup-console-values=false

# Custom Application Batch Configuration
batch.chunk-size=24000
batch.partitions=8
batch.job-name=csvToDbJob
batch.file-path=data/large_books.csv
